MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();

            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {

            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.KATEGORIAD,
                                                Value=i.KATEGORIID.ToString()
                                            }).ToList();
            ViewBag.dgr = degerler;//diğer sayfaya taşımak için. değerleri taşıyacağız. değerler napıyo sorgudan gelen değerleri tutuyo onuda dgr nin içine attık

            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            //Yeni Bir Kategori ekleme işlemini gerçekleştireceğiz.Ysni ürün içeriside bu kez kategoriyi dropdowndan seçip ekleyeceğiz
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);         
            db.SaveChanges();
            return RedirectToAction("Index");//kaydetme işlmeini yaptıktan sonra bizi ındex sayfasına geri yönlendirsin.
        }
        public ActionResult SIL(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLER.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;//diğer sayfaya taşımak için. değerleri taşıyacağız. değerler napıyo sorgudan gelen değerleri tutuyo onuda dgr nin içine attık


            return View("UrunGetir", urun);

        }
        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;
            //urun.URUNKATEGORI = p.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>Ürün ID</th>
            <th>Ürün Adı</th>
            <th>Markası</th>
            <th>Kategori</th>
            <th>Fiyat</th>
            <th>Stok</th>
            <th>SiL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.URUNID</th>
                <td>@urn.URUNAD</td>
                <td>@urn.MARKA</td>
                <td>@urn.TBLKATEGORILER.KATEGORIAD</td>
                @*İnner join gibi düşün .birleştirme işlemi*@
                <td>@urn.FIYAT</td>
                <td>@urn.STOK</td>
                <td><a href="/URUN/SIL/@urn.URUNID" class="btn btn-danger">SİL</a></td>
                <td><a href="/URUN/UrunGetir/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td>


            </tr>
        }


    </tbody>



</table>
<a href="/URUN/UrunEkle/" class="btn btn-primary">YENİ ÜRÜN EKLE</a>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script>
    $('#tbl1').DataTable();

</script>

MvcStok/Views/Urun/UrunEkle.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form method="post" class="form-group">
        @*required alanı boş geçezmezsin mesajı verir*@
        <div>
            <label>Ürün Adı</label>
            <input type="text" class="form-control" name="URUNAD" required="" placeholder="Buraya adı yazınız " maxlength="30" />

        </div>
        <div>
            <label>Markası</label>
            <input type="text" class="form-control" name="MARKA" required="" placeholder="Buraya Markayı Giriniz" />

        </div>
        <div>
            <label>Kategori Seçiniz</label>
            @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })

        </div>
        <div>
            <label>Fiyatı</label>
            <input type="text" class="form-control" name="FIYAT" required="" placeholder="Buraya Fiyat Değerini Giriniz" />

        </div>
        <div>
            <label>Stok Adet</label>
            <input type="text" class="form-control" name="STOK" required="" placeholder="Buraya Stok Adetini Giriniz" />

        </div>
        <div>
            <button class="btn btn-info" id="btnurunekle">Ürün Ekle</button>
            <script>
                $('#btnurunekle').click(function () {
                    alert('Ürün Ekleme İşlemi Yapıldı...!!');
                });

            </script>
        </div>
        
    </form>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using(Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" }) 
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
        @*@Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })*@
        <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })


    </div>
<div>
    <button class="btn btn-warning">Ürün Güncelle</button>
</div>
}