MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERILER select d;//değerleri d üstünden alıyor direk listeyi döndürüyor.Parametre boşsa bunu yap değilse ifle olan komuta git
            if(!string.IsNullOrEmpty(p))
            {
                //Eğerki p değeri boş değilse vey NULL DEĞİLSE o zaman burdaki işlemi gerçekleştir. Ama listeyi döndürücek (yukardaki)
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));//müşteri adı içerisinde parametreye eşit olan değerleri bana getirecek

            }
            return View(degerler.ToList());

           // var degerler = db.TBLMUSTERILER.ToList();
           // return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)//doğrulama  işlemi yapılmadıysa
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", mus);

        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
{
    <p>
        <b>Aranacak Müşteri Adı:</b> @Html.TextBox("p")
        <input type="submit" value="Ara" />

    </p>
}

<table class="table table-bordered ">


    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
        <th>SiL</th>
        <th>GÜNCELLE</th>
        @*<th>ALERT</th>*@
    </tr>
    <tbody>
        @foreach (var mus in Model)
        {
        <tr>
            <th>@mus.MUSTERIID</th>
            <td>@mus.MUSTERIAD</td>
            <td>@mus.MUSTERISOYAD</td>
            <td>@Html.ActionLink("SİL", "SIL", new { id = mus.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Silmek İstediğinize Emin Misiniz?')" })</td>
            @*<td><a href="/MUSTERI/SIL/@mus.MUSTERIID" class="btn btn-danger">SİL</a></td>*@
            <td><a href="/MUSTERI/MusteriGetir/@mus.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>

            @*Burda silmek istediğinize emin misiniz mesajı yazıyor Sonra!! oncliğin türevlerine bak *@
            @*<td>@Html.ActionLink("SİL BUTONU", "SIL", new { id = mus.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Silmek İstediğinize Emin Misiniz?')" })</td>*@

        </tr>
            }


    </tbody>

</table>
<a href="/Musteri/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using(Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERISOYAD)
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>
}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form method="post" class="form-group">
        <div>
            <label>Müşteri Adı</label>
             @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
             @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new {@style="color:green"})

        </div>
        <div>
            <label>Müşteri Soyadı</label>
            <input type="text" class="form-control" name="MUSTERISOYAD" />

        </div>
        <div style="margin-top:15px">
            <button class="btn btn-info" id="btn1"  >Müşteri Ekle</button> 
            <script>

                $('#btn1').click(function ()
                {
                    alert('Müşteri Ekleme İşlemi Yapıldı...!!');
                });

            </script>
        </div>
    </form>